CREATE TABLE Answer
(
  answerId VARCHAR(255) PRIMARY KEY,
  body TEXT NOT NULL,
  userId VARCHAR(255) NOT NULL,
  questionId VARCHAR(255) NOT NULL,
  preffered BIT NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT GETDATE(),
  FOREIGN KEY (userId) REFERENCES Users(userId),
  FOREIGN KEY (questionId) REFERENCES Question(questionId) ON DELETE CASCADE
);
