CREATE TABLE AnswerComment
(
    commentId VARCHAR(255) PRIMARY KEY,
    body TEXT NOT NULL,
    userId VARCHAR(255) NOT NULL,
    answerId VARCHAR(255) NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (userId) REFERENCES Users(userId),
    FOREIGN KEY (answerId) REFERENCES Answer(answerId) ON DELETE CASCADE
);
