CREATE TABLE Question
(
  questionId VARCHAR(255) PRIMARY KEY,
  title VARCHAR(MAX) NOT NULL,
  body TEXT,
  userId VARCHAR(255) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT GETDATE(),
  FOREIGN KEY (userId) REFERENCES Users(userId) ON DELETE CASCADE
);
